name: vue-tz-agi
services:

  api:
    build:
      context: .
      dockerfile: conf/api/Dockerfile
    networks:
      - node_network

  nginx:
    build:
      context: .
      dockerfile: conf/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - node_network

networks:
  node_network: